import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { BottomNav, colors, SectionLabel } from '@/components/ui';
import { Icon } from '@/components/icon';
import { getProducts, Product } from '@/lib/marketplace';

type Tab = 'Top Brands' | 'Nearby Stores' | '1Fi Marketplace';
export default function ShopScreen() {
  const [tab, setTab] = useState<Tab>('1Fi Marketplace'); const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [query, setQuery] = useState('');
  const load = () => { setLoading(true); setError(false); getProducts().then(setProducts).catch(() => setError(true)).finally(() => setLoading(false)); };
  useEffect(load, []);
  const visible = products.filter(p => `${p.name} ${p.brand}`.toLowerCase().includes(query.toLowerCase()));
  return <SafeAreaView style={s.safe}><FlatList data={tab === '1Fi Marketplace' ? visible : []} keyExtractor={p => p.id} contentContainerStyle={s.content} ListHeaderComponent={<>
    <LinearGradient colors={['#2B0F90', '#7827DB']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={s.hero}><Text style={s.eyebrow}>✦ NO-COST EMIS</Text><Text style={s.heroTitle}>Shop today,{`\n`}<Text style={s.italic}>pay later</Text> using{`\n`}mutual funds.</Text><Text style={s.heroSub}>No credit score required. No interest.{`\n`}Backed by your investments.</Text><Icon name="bag-handle" size={90} color="#F7C846" style={s.heroIcon} /></LinearGradient>
    <View style={s.tabs}>{(['Top Brands', 'Nearby Stores', '1Fi Marketplace'] as Tab[]).map(item => <Pressable key={item} onPress={() => setTab(item)} style={[s.tab, tab === item && s.tabActive]}><Text numberOfLines={1} style={[s.tabText, tab === item && s.tabTextActive]}>{item.replace('1Fi ', '')}</Text>{tab === item && <View style={s.underline} />}</Pressable>)}</View>
    {tab !== '1Fi Marketplace' ? <View style={s.empty}><Icon name="storefront" size={54} color="#B8ADC9" /><Text style={s.emptyTitle}>{tab}</Text><Text style={s.emptySub}>This section is intentionally left blank for the assignment.</Text></View> : <><View style={s.search}><Icon name="search" color="#9096A4" size={22} /><TextInput value={query} onChangeText={setQuery} placeholder="Search products..." placeholderTextColor="#A0A4AE" style={s.input} /></View><SectionLabel>1FI MARKETPLACE</SectionLabel><Text style={s.heading}>Shop with no-cost EMI</Text></>}
  </>} renderItem={({ item }) => <Pressable onPress={() => router.push(`/product/${item.id}`)} style={s.card}><Image source={{ uri: item.image }} style={s.productImage} /><View style={s.cardCopy}><Text style={s.brand}>{item.brand}</Text><Text numberOfLines={1} style={s.productName}>{item.name}</Text><Text style={s.price}>₹{item.price.toLocaleString('en-IN')}</Text><Text style={s.emi}>From ₹{item.emiPlans[item.emiPlans.length - 1].monthly.toLocaleString('en-IN')}/mo · 0% interest</Text></View><Icon name="chevron-forward" size={20} color="#9DA1AA" /></Pressable>} ListEmptyComponent={tab === '1Fi Marketplace' ? <>{loading && <ActivityIndicator color={colors.purple} size="large" style={s.loader} />}{error && <Pressable onPress={load} style={s.retry}><Text style={s.retryText}>Couldn’t load products. Tap to retry.</Text></Pressable>}{!loading && !error && <Text style={s.noResults}>No products found.</Text>}</> : null} ListFooterComponent={<View style={{ height: 120 }} />} /></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, content: { paddingBottom: 88 }, hero: { height: 260, borderBottomLeftRadius: 26, borderBottomRightRadius: 26, padding: 28, overflow: 'hidden' }, eyebrow: { alignSelf: 'flex-start', color: '#FFF', borderColor: '#A780F0', borderWidth: 1, borderRadius: 16, paddingHorizontal: 11, paddingVertical: 7, fontWeight: '800', letterSpacing: 1, fontSize: 12 }, heroTitle: { color: 'white', fontSize: 32, lineHeight: 37, fontWeight: '800', marginTop: 15 }, italic: { fontStyle: 'italic', fontWeight: '600' }, heroSub: { color: '#E6DDFE', fontSize: 14, lineHeight: 21, marginTop: 10 }, heroIcon: { position: 'absolute', right: 24, bottom: 34, transform: [{ rotate: '-12deg' }] }, tabs: { marginHorizontal: 20, marginTop: -26, borderRadius: 32, backgroundColor: '#F3EFFF', padding: 6, flexDirection: 'row', height: 64 }, tab: { flex: 1, justifyContent: 'center', alignItems: 'center', position: 'relative', paddingHorizontal: 4 }, tabActive: { backgroundColor: 'white', borderRadius: 27, shadowColor: '#4F2C88', shadowOpacity: .13, shadowRadius: 8, elevation: 3 }, tabText: { fontSize: 13, fontWeight: '700', color: '#777A84' }, tabTextActive: { color: '#6530B7' }, underline: { position: 'absolute', bottom: 8, height: 3, width: 34, borderRadius: 3, backgroundColor: colors.purple }, search: { flexDirection: 'row', alignItems: 'center', margin: 28, marginBottom: 22, paddingHorizontal: 20, height: 58, backgroundColor: 'white', borderRadius: 29, borderColor: colors.line, borderWidth: 1 }, input: { flex: 1, marginLeft: 12, fontSize: 16, color: colors.ink }, heading: { fontSize: 27, color: colors.ink, fontWeight: '800', marginHorizontal: 28, marginBottom: 16 }, card: { marginHorizontal: 20, marginBottom: 14, borderRadius: 20, backgroundColor: 'white', padding: 12, borderColor: colors.line, borderWidth: 1, flexDirection: 'row', alignItems: 'center' }, productImage: { width: 82, height: 82, borderRadius: 14, backgroundColor: '#EEEAF4' }, cardCopy: { flex: 1, marginLeft: 15 }, brand: { color: colors.purple, fontWeight: '800', fontSize: 12 }, productName: { color: colors.ink, fontWeight: '800', fontSize: 17, marginTop: 2 }, price: { color: colors.ink, fontWeight: '700', fontSize: 15, marginTop: 8 }, emi: { color: '#777C89', fontSize: 12, marginTop: 2 }, loader: { marginTop: 40 }, retry: { margin: 28, padding: 16, backgroundColor: '#F1EAFF', borderRadius: 14 }, retryText: { color: '#5923AA', textAlign: 'center', fontWeight: '700' }, noResults: { textAlign: 'center', color: colors.muted, marginTop: 34 }, empty: { alignItems: 'center', margin: 54, gap: 12 }, emptyTitle: { color: colors.ink, fontSize: 22, fontWeight: '800' }, emptySub: { color: colors.muted, textAlign: 'center', lineHeight: 20 } });
