import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors, PrimaryButton, SectionLabel } from '@/components/ui';
import { Icon } from '@/components/icon';
import { EmiPlan, getProduct, Product } from '@/lib/marketplace';

export default function ProductScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [product, setProduct] = useState<Product>(); const [variant, setVariant] = useState(''); const [plan, setPlan] = useState<EmiPlan>(); const [error, setError] = useState('');
  useEffect(() => { if (id) getProduct(id).then(p => { setProduct(p); setVariant(p.variants[0]); setPlan(p.emiPlans[0]); }).catch(e => setError(e.message)); }, [id]);
  if (error) return <SafeAreaView style={s.center}><Icon name="alert-circle-outline" size={52} color={colors.purple} /><Text style={s.error}>{error}</Text><PrimaryButton title="Go back" onPress={() => router.back()} /></SafeAreaView>;
  if (!product || !plan) return <SafeAreaView style={s.center}><ActivityIndicator size="large" color={colors.purple} /></SafeAreaView>;
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Pressable onPress={() => router.back()} style={s.back}><Icon name="arrow-back" size={23} color={colors.ink} /></Pressable><Image source={{ uri: product.image }} style={s.image} /><Text style={s.brand}>{product.brand.toUpperCase()}</Text><Text style={s.title}>{product.name}</Text><Text style={s.price}>₹{product.price.toLocaleString('en-IN')}</Text><Text style={s.description}>{product.description}</Text><View style={s.divider} />
  <SectionLabel>SELECT VARIANT</SectionLabel><View style={s.chips}>{product.variants.map(item => <Pressable key={item} onPress={() => setVariant(item)} style={[s.chip, item === variant && s.chipActive]}><Text style={[s.chipText, item === variant && s.chipTextActive]}>{item}</Text></Pressable>)}</View>
  <View style={s.divider} /><SectionLabel>CHOOSE EMI PLAN</SectionLabel><Text style={s.note}>0% interest. Your investments remain invested.</Text>{product.emiPlans.map(item => <Pressable key={item.months} onPress={() => setPlan(item)} style={[s.plan, item.months === plan.months && s.planActive]}><View style={[s.radio, item.months === plan.months && s.radioActive]}>{item.months === plan.months && <View style={s.radioDot} />}</View><View style={s.planCopy}><Text style={s.months}>{item.months} months</Text><Text style={s.total}>Total ₹{item.total.toLocaleString('en-IN')}</Text></View><View><Text style={s.monthly}>₹{item.monthly.toLocaleString('en-IN')}/mo</Text><Text style={s.noCost}>{item.savings}</Text></View></Pressable>)}
  <View style={{ height: 105 }} /></ScrollView><View style={s.footer}><Text style={s.footerAmount}>₹{plan.monthly.toLocaleString('en-IN')}/month<Text style={s.footerMonths}> for {plan.months} months</Text></Text><PrimaryButton title="Proceed with this plan" onPress={() => router.push({ pathname: '/success', params: { product: product.name, months: String(plan.months), amount: String(plan.monthly) } })} /></View></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, content: { padding: 20 }, center: { flex: 1, padding: 28, justifyContent: 'center', gap: 20, backgroundColor: colors.canvas }, error: { color: colors.ink, fontSize: 18, textAlign: 'center' }, back: { backgroundColor: 'white', height: 44, width: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center', marginBottom: 12, borderWidth: 1, borderColor: colors.line }, image: { width: '100%', height: 270, borderRadius: 24, backgroundColor: '#EDEAF3' }, brand: { marginTop: 24, color: colors.purple, fontWeight: '800', letterSpacing: 1.5, fontSize: 12 }, title: { color: colors.ink, fontSize: 30, fontWeight: '800', marginTop: 5 }, price: { color: colors.ink, fontSize: 21, fontWeight: '800', marginTop: 8 }, description: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 12 }, divider: { height: 1, backgroundColor: colors.line, marginVertical: 26 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, chip: { paddingHorizontal: 16, paddingVertical: 12, borderRadius: 20, borderWidth: 1, borderColor: '#DCD8E3', backgroundColor: 'white' }, chipActive: { borderColor: colors.purple, backgroundColor: colors.lavender }, chipText: { color: '#656A74', fontWeight: '700' }, chipTextActive: { color: colors.purple }, note: { color: colors.muted, marginTop: -5, marginBottom: 14 }, plan: { borderWidth: 1, borderColor: colors.line, borderRadius: 18, backgroundColor: 'white', minHeight: 82, padding: 15, flexDirection: 'row', alignItems: 'center', marginBottom: 11 }, planActive: { borderColor: colors.purple, backgroundColor: '#FCFAFF' }, radio: { height: 21, width: 21, borderRadius: 12, borderWidth: 2, borderColor: '#B4B3BA', alignItems: 'center', justifyContent: 'center' }, radioActive: { borderColor: colors.purple }, radioDot: { height: 11, width: 11, borderRadius: 6, backgroundColor: colors.purple }, planCopy: { flex: 1, marginLeft: 13 }, months: { color: colors.ink, fontWeight: '800', fontSize: 16 }, total: { color: colors.muted, fontSize: 12, marginTop: 3 }, monthly: { color: colors.ink, fontWeight: '800', fontSize: 15, textAlign: 'right' }, noCost: { color: '#32875E', fontSize: 12, fontWeight: '700', marginTop: 3 }, footer: { position: 'absolute', left: 0, right: 0, bottom: 0, backgroundColor: 'white', padding: 16, paddingBottom: 20, borderTopColor: colors.line, borderTopWidth: 1 }, footerAmount: { color: colors.ink, fontSize: 15, fontWeight: '800', marginBottom: 11 }, footerMonths: { color: colors.muted, fontWeight: '500' } });
